version: '3.8'

services:
  backend:
    build: ./backend/CustomerAPI
    ports:
      - "7081:7081"
    environment:
      - ASPNETCORE_URLS=http://+:7081
    networks:
      - app_network

  frontend:
    build: ./frontend/customers-app
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
