services:
  backend:
    build: ./backend
    ports:
      - "7082:7082"
    environment:
      - ASPNETCORE_URLS=http://+:7082
    networks:
      - app_network

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:7082
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
